### ISSUE TITLE
Rewrite code using constant

### ISSUE THREAD

**Issue by Anarasty** [SashaGandzeychuk/lab4_tpr#1]
Hi @SashaGandzeychuk ,
Please, unify check countries input. Instead of hardcoding by storing it in a variable, You should create a new constant min_countries_amount with specific value and specify it in config file like a max_countries_amount constant. Thank you.
https://github.com/SashaGandzeychuk/lab4_tpr/blob/f71fa038fd0eac6623d71f29cecd3eddde5cfc92/src/input.py#L46

**Comment by SashaGandzeychuk** [comment]
I have uploaded changes to the code, please check them

**Comment by Anarasty** [comment]
All fine. Good work!
